server:
  port: 8000
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/osms
    username: osms
    password: osms
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      wrap_root_value: true
logging:
  level:
    org.springframework: INFO
    org.springframework.security: TRACE
    org.springframework.boot: INFO
    org.junit: INFO
    com.oas: DEBUG

app:
  ignoredUrls:
    -
      pattern: /auth/login
      method: POST
    -
      pattern: /auth/register
      method: POST
